app_name: SynthPDF
author: Julian Lu
email: julianlu@wezhuiyi.com

io:
  output_path: 'outputs'
  pdf_path: 'pdfs'
  img_path: 'imgs'
  json_path: 'jsons'

runner:
  n_files: 50000
  run_parallel: true
  num_processors: 46

mixer:
  prob_title: 0.1
  prob_paragraph: 0.6
  prob_spacer: 0.1
  prob_list: 0.2  
  min_tables_per_page: 1
  max_tables_per_page: 3
  max_elements_per_page: 10
  avoid_neighbor_tables: true
  as_img: true
  as_pdf: true
  annotate: true
  save_annotate_imgs: true
  show_annotate_imgs: false
  save_single_annotate_json: true
  ensure_tabel_exist: true

page:
  prob_portrait: 0.7
  prob_landscape: 0.3


table:
  layout:
    nrows: [2, 20]
    ncols: [2, 6]
    space_before: [3, 10]
    space_after: [3, 10] # frame._prevASpace
  cell:
    font_size: [8,13]
    text_color: ['black']  # font name or RGB 
    vertical_align: [] # Opt: ['TOP', 'MIDDLE', 'BOTTOM'] if empty, apply randomly
    horizontal_align: ['CENTER'] # Opt: ['LEFT', 'RIGHT', 'CENTER', 'DECIMAL'] if empty,     
  line:
    grid_prob: 0.5 # The probability of having grid linesx
    grid_color: ['black'] # ['red', 'green', 'grey', 'black', 'pink', 'lavender', 'orange', 'blue', 'yellow']
    grid_line_width: [1, 2]

  space:
    prob_empty_col: 0.5
    size_empty_col: [20, 40]
    prob_empty_row: 0.3
    
  content:
    blocks: # prob of having cn/en/num in tabe hearders
      prob_empty_first_cell: 0.6
      col_header: # need to sum to 1
        prob_number: 0.1
        prob_cn_char: 0.8
        prob_en_char: 0.1
        wrap: 0.5
      row_header: # need to sum to 1 
        prob_number: 0.1
        prob_cn_char: 0.8
        prob_en_char: 0.1
        wrap: 0.25
      content: # prob of having cn/en/num in tabel contents
        prob_number: 0.6 # need to sum to 1 
        prob_cn_char: 0.1
        prob_en_char: 0.0
        prob_percent: 0.3
        wrap: 0.1
    numbers: # number details 
      n_integers: [1, 7]
      n_digits: [0, 4]
    cn_chars: # cn char details
      word_length: [1, 6]
    en_chars: # en char detils 
      word_length: [1, 8]
    special: # special char details [no need to sum to 1]
      prob_parentheses: 0.3
      prob_empty: 0.1
      prob_dash: 0.15
      prob_underline: 0.3 # currently not supported for table 

paragraph:
  long:
    prob: 0.6
    n_sentences: [5, 20]
    sentence_length: [2, 10]
  short:
    prob: 0.4
    n_sentences: [1, 3]
    sentence_length: [2, 5]
  font_size: [8, 14]
  leading: [0.8, 2.0]    # line gap 
  text_color: ['black']  # font name or RGB
  align: [] # Opts: justify, center, left, right
  space_before: [3, 15] # space above the paragrah block
  space_after: [3, 15] # space below the paragrah block
  firstline_indent: [0, 12, 24, 32]
  
title:
  n_lines: [1, 3]
  font_size: [15, 22]
  leading: [1, 1.5]
  text_color: ['black']
  sentence_length: [2, 10]
  n_sentences: [1,2]
  align: ['center']
  space_before: [5, 10]
  space_after: [5, 10]
  firstline_indent: [0]
  
list:
  n_bullet: [3, 6]
  n_sentences: [1, 3]
  sentence_length: [2, 5]
  firstline_indent: [0]
  leading: [0.8, 2.0]
  text_color: ['black']
  align: ['left']
  font_size: [10, 15]
  space_before: [2, 10]
  space_after: [2, 10]
  
spacer:
  height: [1, 5]

notFlowables:
  stamp: # currently only add to bordered table corners
    prob: 0.3
    n_stamps: [1, 4]
    corner_dx: [-30, 30]
    corner_dy: [-30, 30]
    width: [30, 70]
    stamp_img_path: img_data/stamps