app_name: SynthPDF
author: Julian Lu
email: julianlu@wezhuiyi.com

###
# NOTE: items start with 'prob_' at the save structure level are automatically parsed 
#       using their probability value

io:
  output_path: 'outputs'
  pdf_path: 'pdfs'
  img_path: 'imgs'
  json_path: 'jsons'

runner:
  n_files: 40
  run_parallel: true
  num_processors: 4

page:
  prob_portrait: 1
  prob_landscape: 0
  
  header:
    line:
      center: true           # if true, right_margin is overwritten by left_margin 
      top_margin: [30, 60]
      left_margin: [10, 40]
      right_margin: [10, 15]
      linewidth: [1,2]
    text:
      locations: ['left', 'right', 'center']
      word_length: [2, 8]
      font_size: [5, 13]
     
      
  footer:
    page_number: true
    
table:
  layout:
    nrows: [25, 40]
    ncols: [3, 5]
    space_before: [3, 12]
    space_after: [3, 12] # frame._prevASpace
  cell:
    font_size: [8,13]
    text_color: ['black']  # font name or RGB 
    vertical_align: [] # Opt: ['TOP', 'MIDDLE', 'BOTTOM'] if empty, apply randomly
    horizontal_align: ['CENTER'] # Opt: ['LEFT', 'RIGHT', 'CENTER', 'DECIMAL'] if empty,     
  line:
    prob_no_grid: 0.5     # prob having no grid lines at all 
    prob_full_grid: 0.15   # prob having full gird lines 
    prob_hline_only: 0.15  # prob having horizonal grid lines only 
    prob_head_hline_2: 0.1  # prob having only first two hlines
    prob_head_hline_1: 0.1  # prob having only one hlines under first row 
    grid_prob: 0.5 # The probability of having grid lines
    grid_color: ['black'] # ['red', 'green', 'grey', 'black', 'pink', 'lavender', 'orange', 'blue', 'yellow']
    grid_line_width: [1, 2]

  space:
    prob_empty_col: 0.05
    size_empty_col: [20, 45]
    prob_empty_row: 0.2
    prob_empty_second_row: 0.4
    prob_empty_last_second_row: 0.3
    
  content:
    blocks: # prob of having cn/en/num in tabe hearders
      prob_empty_first_cell: 0.6
      col_header: # need to sum to 1
        prob_number: 0.1
        prob_cn_char: 0.8
        prob_en_char: 0.1
        wrap: 0.4
      row_header: # need to sum to 1 
        prob_number: 0.1
        prob_cn_char: 0.6
        prob_en_char: 0.1
        prob_punctuation: 0.2
        wrap: 0.3
      content: # prob of having cn/en/num in tabel contents
        prob_number: 0.5 # need to sum to 1 
        prob_cn_char: 0.3
        prob_en_char: 0.0
        prob_percent: 0.2
        wrap: 0.1
    numbers: # number details 
      n_integers: [1, 7]
      n_digits: [0, 4]
    cn_chars: # cn char details
      word_length: [1, 6]
    en_chars: # en char detils 
      word_length: [1, 8]
    special: # special char details [no need to sum to 1]
      prob_parentheses: 0.3
      prob_empty: 0.15
      prob_dash: 0.15
      prob_underline: 0.3 # currently not supported for table 
  
  
  
spacer:
  height: [1, 5]

notFlowables:
  stamp: # currently only add to bordered table corners
    n: [1, 4]
    prob: 0.3
    corner_dx: [-20, 20]
    corner_dy: [-20, 20]
    width: [30, 70]
    img_path: img_data/stamps
  signature: # currently only add to bordered table corners
    n: [1, 4]
    prob: 0.3
    corner_dx: [-20, 20]
    corner_dy: [-20, 20]
    width: [30, 70]
    img_path: img_data/signatures


