app_name: SynthPDF
author: Julian Lu
email: julianlu@wezhuiyi.com

runner:
  n_files: 30
  run_parallel: true
  num_processors: 8

io:
  output_path: 'outputs'
  pdf_path: 'pdfs'
  img_path: 'imgs'
  json_path: 'jsons'

mixer:
  prob_title: 0.2
  prob_paragraph: 0.7
  prob_spacer: 0.1
  min_tables_per_page: 0
  max_tables_per_page: 4
  avoid_neighbor_tables: true
  max_elements_per_page: 6
  as_img: true
  as_pdf: true
  annotate: true
  save_annotate_imgs: true
  show_annotate_imgs: false
  save_single_annotate_json: true


table:
  layout:
    nrows: [1, 20]
    ncols: [2, 6]
    space_before: [3, 10]
    space_after: [3, 10] # frame._prevASpace

  cell:
    font_size: [6,13]
    text_color: ['black']  # font name or RGB 
    vertical_align: [] # Opt: ['TOP', 'MIDDLE', 'BOTTOM'] if empty, apply randomly
    horizontal_align: ['CENTER'] # Opt: ['LEFT', 'RIGHT', 'CENTER', 'DECIMAL'] if empty, 

  line:
    grid_prob: 0.5 # The probability of having grid linesx
    grid_color: ['black'] # ['red', 'green', 'grey', 'black', 'pink', 'lavender', 'orange', 'blue', 'yellow']
    grid_line_width: [1, 3]

  content:
    blocks: # prob of having cn/en/num in tabe hearders
      col_header: # need to sum to 1
        prob_number: 0.1
        prob_cn_char: 0.8
        prob_en_char: 0.1
      row_header: # need to sum to 1 
        prob_number: 0.1
        prob_cn_char: 0.8
        prob_en_char: 0.1
      content: # prob of having cn/en/num in tabel contents
        prob_number: 0.6 # need to sum to 1 
        prob_cn_char: 0.1
        prob_en_char: 0.0
        prob_percent: 0.3
    numbers: # number details 
      n_integers: [1, 7]
      n_digits: [0, 4]
    cn_chars: # cn char details
      word_length: [1, 6]
    en_chars: # en char detils 
      word_length: [1, 8]
    special: # special char details [no need to sum to 1]
      prob_parentheses: 0.3
      prob_empty: 0.1
      prob_dash: 0.15
      #prob_underline: 0.3 # currently not supported for table 

paragraph:
  long:
    prob: 0.5
    n_sentences: [1, 30]
    sentence_length: [2, 60]
  short:
    prob: 0.5
    n_sentences: [1, 3]
    sentence_length: [2, 5]
  font_size: [8, 14]
  leading: [0.8, 2.0]    # line gap 
  text_color: ['black']  # font name or RGB
  align: [] # Opts: justify, center, left, right
  space_before: [3, 15] # space above the paragrah block
  space_after: [3, 15] # space below the paragrah block

title:
  n_lines: [1, 3]
  font_size: [15, 22]
  leading: [1, 1.5]
  text_color: ['black']
  sentence_length: [2, 10]
  n_sentences: [1,2]
  align: ['center']
  space_before: [5, 10]
  space_after: [5, 10]

spacer:
  height: [1, 3]