app_name: SynthPDF



chars:
  cn_char_file: 'char_data/JianTi3500.txt'
  symbol_char_file: 'char_data/FuHao110.txt'
  number_char_file: 'char_data/ShuZiZiMu62.txt'


mixer:
  prob_title: 0.2
  prob_paragraph: 0.7
  prob_spacer: 0.1
  min_tables_per_page: 0
  max_tables_per_page: 4
  max_elements_per_page: 6
  as_img: true
  as_pdf: true
  annotate: true


table:
  layout:
    nrows: [1, 15]
    ncols: [2, 5]
    space_before: [1, 5]
    space_after: [1, 5]
    
  cell:
    font_size: [6,13]
    text_color: ['black']  # font name or RGB 
    vertical_align: [] # Opt: ['TOP', 'MIDDLE', 'BOTTOM'] if empty, apply randomly
    horizontal_align: ['CENTER'] # Opt: ['LEFT', 'RIGHT', 'CENTER', 'DECIMAL'] if empty, 
    
  line:
    grid_prob: 0.5 # The probability of having grid linesx
    grid_color: ['red', 'green', 'grey', 'black', 'pink', 'lavender', 'orange', 'blue', 'yellow']
    grid_line_width: [1]

paragraph:
  n_sentences: [1, 20]
  sentence_length: [2, 40]
  font_size: [8, 15]
  leading: [0.8, 3.0]
  text_color: ['black']  # font name or RGB
  align: [] # Opts: justify, center, left, right 

title:
  n_lines: [1, 3]
  font_size: [15, 22]
  leading: [0.9, 2.0]
  text_color: ['black']
  sentence_length: [2, 10]
  n_sentences: [1,2]
  align: ['center']


spacer:
  height: [1, 5]